import type { Metadata } from "next";
import "./globals.css";
import { auth } from "./auth";
import SignIn from "./components/SignIn";
import LoggedInBar from "./components/LoggedInBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const session = await auth();

  return (
    <html lang="en">
      <body>
        <LoggedInBar />
        { session ? children : <SignIn /> }
      </body>
    </html>
  );
}
